# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-14 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=64)),
                ('cust_local', models.CharField(max_length=256)),
                ('cust_mobile_phone', models.CharField(default='-', max_length=32)),
                ('cust_phone_number', models.CharField(default='-', max_length=32)),
                ('cust_rebate', models.FloatField(default=100.0)),
                ('cust_address', models.CharField(max_length=1024)),
                ('is_delete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'syc_cust_info',
            },
        ),
    ]
