# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-14 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pur_location_name', models.CharField(max_length=64)),
                ('pur_cust_name', models.CharField(max_length=64)),
                ('pur_price', models.FloatField(default=0.0)),
                ('pur_create_date', models.DateTimeField(auto_now_add=True)),
                ('pur_modify_date', models.DateField(default='2018-09-14')),
                ('pur_finished_date', models.DateField(auto_now=True)),
                ('pur_handle', models.CharField(max_length=256)),
                ('is_finished', models.BooleanField(default=0)),
                ('is_delete', models.BooleanField(default=0)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='information.CustomerInfo')),
            ],
            options={
                'db_table': 'syc_purchase',
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pur_pro_id', models.CharField(max_length=64)),
                ('pur_pro_type', models.CharField(max_length=256)),
                ('pur_pro_count', models.IntegerField(default=0)),
                ('pur_finished_pro_count', models.IntegerField(default=0)),
                ('pur_pro_unit_price', models.FloatField(default=0.0)),
                ('pur_pro_price', models.FloatField(default=0.0)),
                ('is_delete', models.BooleanField(default=0)),
                ('pur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.Purchase')),
            ],
            options={
                'db_table': 'syc_pur_detail',
            },
        ),
    ]
