# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-19 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='pur_modify_date',
            field=models.DateField(default='2018-09-19'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='pur_half_finished_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.StorageHalfFinished', to_field='half_id'),
        ),
    ]
